version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
    volumes:
      - .etc/docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.0
    #command: -v start --import-realm
    # export command
    #entrypoint: /opt/keycloak/bin/kc.sh export --file /data/test-realm.json
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    links:
      - mysql
      - maildev
    volumes:
      # export command
      - ./sdk/e2e/fixtures/auth-utils/test-realm.json:/data/test-realm.json
      - ./spi/target/keycloak-auditor-spi.jar:/opt/keycloak/providers/keycloak-auditor-spi.jar
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_SCHEMA: ${MYSQL_DATABASE}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      KC_AUD_GLOBAL_MASTER_ACCESS: 'true'

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - '8081:80'
      - '25'