version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
    volumes:
      - .etc/docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    # export command
    #entrypoint: /opt/keycloak/bin/kc.sh export --file /exports/export.json
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    links:
      - mysql
      - maildev
    volumes:
      # export command
      #- ./spi/src/test/resources/test-realm.json:/exports/export.json
      - ./spi/target/keycloak-auditor-spi.jar:/opt/keycloak/providers/keycloak-auditor-spi.jar
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_SCHEMA: ${MYSQL_DATABASE}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'

  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - '8081:80'
      - '25'
