# Ignore GitHub Actions rule S7637 across the repository
sonar.issue.ignore.multicriteria=ghaS7637
sonar.issue.ignore.multicriteria.ghaS7637.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.ghaS7637.resourceKey=.github/workflows/**/*
