sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S7636
sonar.issue.ignore.multicriteria.e1.resourceKey=**/.github/workflows/**/*.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=githubactions:S7630
sonar.issue.ignore.multicriteria.e2.resourceKey=**/.github/workflows/**/*.yml
sonar.issue.ignore.multicriteria.e3.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.e3.resourceKey=**/.github/workflows/**/*.yml
