name: Release

on:
  release:
    types: [created]

jobs:
  deploy_mvn:
    name: Deploy Maven Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Publish mvn package
        run: mvn --batch-mode package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release latest version
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: keycloak-auditor-spi.jar
          file: spi/target/keycloak-auditor-spi.jar
          tag: ${{ github.ref }}
          overwrite: true
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd sdk && npm run clean && npm run build
      - name: Publish npm package
        run: cd sdk && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
